# backend/app/ai/reranker.py

from typing import List, Dict, Any


class Reranker:
    """
    Reranks retrieved evidence based on relevance.

    The initial implementation uses the similarity score
    generated by the vector store.
    """

    def __init__(self, min_score: float = 0.0):
        self.min_score = min_score

    def rerank(
        self,
        query: str,
        documents: List[Dict[str, Any]],
        top_k: int = 5,
    ) -> List[Dict[str, Any]]:
        """
        Rerank documents according to their similarity score.

        Parameters:
            query: Original claim/query.
            documents: Documents returned by vector_store.
            top_k: Number of results to return.
        """

        if not documents:
            return []

        # Remove documents below the minimum relevance score
        filtered_documents = [
            document
            for document in documents
            if document.get("similarity", 0.0) >= self.min_score
        ]

        # Highest similarity first
        ranked_documents = sorted(
            filtered_documents,
            key=lambda document: document.get(
                "similarity",
                0.0
            ),
            reverse=True,
        )

        return ranked_documents[:top_k]


# Shared reranker instance
reranker = Reranker()


def rerank_results(
    query: str,
    documents: List[Dict[str, Any]],
    top_k: int = 5,
) -> List[Dict[str, Any]]:
    """
    Convenience function for reranking evidence.
    """

    return reranker.rerank(
        query=query,
        documents=documents,
        top_k=top_k,
    )